### ISSUE TITLE
CSS preventing tables from displaying correctly

### ISSUE THREAD

**Issue by skydusk** [brijeshb42/bitwiser#8]
Hey again brijesh. The stylesheet is suppressing the borders of tables so they can't display correctly.

raw post on github displays the first 3 tables fine:
https://github.com/skydusk/skydusk.github.io/blob/master/_posts/2015-08-31-crashplan-memory.md

but on the site none of them show properly:
http://skydusk.com/2015/08/31/crashplan-memory.html

**Comment by skydusk** [comment]
Currently the quick fix someone suggested was to add this to style.scss

table, th, td {
   border: 1px solid black;
}


It works and gives the table borders, but it looks ugly. Would prefer the regular markdown table to work if possible. Thanks

**Comment by brijeshb42** [comment]
Edit: I have made a latest commit to `style.scss` file. You can import the changes or do the following:

You can add the following css at the end of `style.scss`:

``` css
table {
  margin: 10px 0px;
}
th, td {
  padding: 10px;
  border: 1px solid #ccc;
}
```

**This is what it looks like after adding the above css**

<img width="609" alt="screen shot 2015-09-02 at 10 49 41 am" src="https://cloud.githubusercontent.com/assets/717550/9623575/60fc2490-5160-11e5-9c27-1d52ecf00f32.png">

**Comment by skydusk** [comment]
That looks much better and blends in with the overall Bitwiser design, thanks Brijesh. If possible is there an easy way to fill the cells with a light grey colour like github does by default? Sort of like this: 

https://raw.githubusercontent.com/skydusk/skydusk.github.io/master/assets/table.png

**Comment by brijeshb42** [comment]
The odd, even color differentiation is just a matter of styling. You can add this:

``` css
table tr:nth-child(even) td {
    background-color: #e8ecee
}
table tr:nth-child(odd) td {
    background-color: #fffbae;
}
```
